
-- Inserts de Pais -- 

-- select * from cgmbr.pais

-- desc cgmbr.pais

INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Afeganistão');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'África do Sul');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Albânia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Alemanha');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Andorra');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Angola');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Anguilla');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Antárctida');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Antigua e Barbuda');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Antilhas Holandesas');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Arábia Saudita');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Argélia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Argentina');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Armênia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Aruba');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Austrália');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Áustria');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Azerbaijão');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Bahrein');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Bangladesh');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Barbados');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Bélgica');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Belize');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Benin');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Bermudas');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Bolívia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Bósnia Herzegovina');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Brasil');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Brunei');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Bulgária');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Burkina Faso');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Burundi');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Butão');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Cabo Verde');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Camarões');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Cambodja');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Canadá');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Catar');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Cazaquistão');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Chade');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Chile');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'China');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'China (Taiwan)');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Chipre');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Colômbia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Comunidade Das Bahamas');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Congo');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Coréia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Coreia do Norte');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Costa Do Marfim');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Costa Rica');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Croácia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Cuba');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Dinamarca');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Djibuti');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Dominica');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Emirados Árabes Unidos');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Equador');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Eritreia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Eslováquia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Eslovênia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Espanha');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Estado Da Cidade Do Vaticano');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Estados Federados da Micronésia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Estados Unidos Da América (Eua)');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Estônia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Etiópia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Filipinas');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Finlândia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'França');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Gâmbia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Gana');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Geórgia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Gibraltar');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Granada');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Grécia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Groenlândia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Guadeloupe');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Guam');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Guatemala');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Guernsey');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Guiana');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Guiana Francesa');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Guiné Bissau');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Guiné Equatorial');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Guiné-Conacri');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Holanda');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Honduras');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Hong');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Hungria');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Iemen');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Ilha Bouvet');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Ilha Christmas');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Ilha de Man');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Ilha Heard e Ilhas McDonald');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Ilha Norfolk');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Ilhas Aland');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Ilhas Cayman');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Ilhas Cocos');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Ilhas Cook');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Ilhas Faroe');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Ilhas Geórgia do Sul e Sandwich do Sul');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Ilhas Malvinas (Falkland)');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Ilhas Marshall');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Ilhas Menores Distantes dos Estados UnidoS');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Ilhas Salomão');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Ilhas Virgens Americanas');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Ilhas Virgens Britânicas');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Índia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Indonésia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Inglaterra');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Irã');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Iraque');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Irlanda Do Norte');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Islândia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Israel');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Itália');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Jamaica');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Japão');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Jersey');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Jordânia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Kiribati');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Kuwait');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Laos');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Lesoto');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Letônia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Líbano');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Libéria');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Líbia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Liechtenstein');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Lituânia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Luxemburgo');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Macau');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Madagascar');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Malásia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Malawi');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Maldivas');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Mali');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Marianas Setentrionais');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Marrocos');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Martinica');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Maurícia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Mauritânia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Mayotte');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'México');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Mianmar');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Moçambique');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Moldávia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Mônaco');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Mongólia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Monte Serrat');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Montenegro');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Namíbia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Nauru');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Nepal');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Nicarágua');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Nigéria');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Niue');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Noruega');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Nova Caledónia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Nova Zelândia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Oman');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Palau');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Palestina');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Panamá');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Papua Nova Guiné');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Paquistão');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Paraguai');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Peru');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Pitcairn');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Polinésia Francesa');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Polônia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Porto Rico');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Portugal');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Quênia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Quirguistão');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'República Árabe Do Egito');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'República Centro-africana');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'República Da Bielorrússia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'República Da Macedônia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'República De El Salvador');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'República De Fiji');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'República De Malta');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'República Democrática do Congo (antigo Zaire)');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'República Do Gabão');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'República Do Haiti');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'República Do Níger');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'República Dominicana');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'República Tcheca');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Reunião');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Romênia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Ruanda');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Rússia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Saara Ocidental');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Saint Martin');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Saint Pierre et Miquelon');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Samoa Americana');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Samoa Ocidental');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'San Marino');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Santa Helena');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Santa Lúcia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'São Bartolomeu');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'São Cristóvão e Névis (Saint Kitts e Nevis)');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'São Tomé E Príncipe');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'São Vicente');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Senegal');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Serra Leoa');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Sérvia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Seychelles');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Singapura');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Síria');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Somália, República');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Sri');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Suazilândia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Sudão');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Suécia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Suíça');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Suriname');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Svalbard e Jan Mayen');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Tadjiquistão');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Tailândia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Tanzânia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Terras Austrais e Antárticas Francesas (TAAF)');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Território Britânico do Oceano Índico');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Timor');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Togo');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Tonga');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Toquelau');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Trinidad E Tobago');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Tunísia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Turcomenistão');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Turks e Caicos');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Turquia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Tuvalu');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Ucrânia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Uganda');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Uruguai');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Uzbequistão');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Vanuatu');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Venezuela');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Vietnã Do Sul');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Wallis e Futuna');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Zâmbia');
INSERT INTO cgmbr.pais (id, version, nome) VALUES (DEFAULT, 1, 'Zimbabwe');

-- Inserte de Estados -- pais 28 Brasil

--desc cgmbr.estado

--select * from cgmbr.estado

INSERT INTO cgmbr.estado (id, version, pais_id, nome, sigla) VALUES (DEFAULT, 1, 28, 'Rondônia','RO');
INSERT INTO cgmbr.estado (id, version, pais_id, nome, sigla) VALUES (DEFAULT, 1, 28, 'Acre','AC');
INSERT INTO cgmbr.estado (id, version, pais_id, nome, sigla) VALUES (DEFAULT, 1, 28, 'Amazonas','AM');
INSERT INTO cgmbr.estado (id, version, pais_id, nome, sigla) VALUES (DEFAULT, 1, 28, 'Roraima','RR');
INSERT INTO cgmbr.estado (id, version, pais_id, nome, sigla) VALUES (DEFAULT, 1, 28, 'Pará','PA');
INSERT INTO cgmbr.estado (id, version, pais_id, nome, sigla) VALUES (DEFAULT, 1, 28, 'Amapá','AP');
INSERT INTO cgmbr.estado (id, version, pais_id, nome, sigla) VALUES (DEFAULT, 1, 28, 'Tocantins','TO');
INSERT INTO cgmbr.estado (id, version, pais_id, nome, sigla) VALUES (DEFAULT, 1, 28, 'Maranhão','MA');
INSERT INTO cgmbr.estado (id, version, pais_id, nome, sigla) VALUES (DEFAULT, 1, 28, 'Piauí','PI');
INSERT INTO cgmbr.estado (id, version, pais_id, nome, sigla) VALUES (DEFAULT, 1, 28, 'Ceará','CE');
INSERT INTO cgmbr.estado (id, version, pais_id, nome, sigla) VALUES (DEFAULT, 1, 28, 'Rio Grande do Norte','RN');
INSERT INTO cgmbr.estado (id, version, pais_id, nome, sigla) VALUES (DEFAULT, 1, 28, 'Paraíba','PB');
INSERT INTO cgmbr.estado (id, version, pais_id, nome, sigla) VALUES (DEFAULT, 1, 28, 'Pernambuco','PE');
INSERT INTO cgmbr.estado (id, version, pais_id, nome, sigla) VALUES (DEFAULT, 1, 28, 'Alagoas','AL');
INSERT INTO cgmbr.estado (id, version, pais_id, nome, sigla) VALUES (DEFAULT, 1, 28, 'Sergipe','SE');
INSERT INTO cgmbr.estado (id, version, pais_id, nome, sigla) VALUES (DEFAULT, 1, 28, 'Bahia','BA');
INSERT INTO cgmbr.estado (id, version, pais_id, nome, sigla) VALUES (DEFAULT, 1, 28, 'Minas Gerais','MG');
INSERT INTO cgmbr.estado (id, version, pais_id, nome, sigla) VALUES (DEFAULT, 1, 28, 'Espírito Santo','ES');
INSERT INTO cgmbr.estado (id, version, pais_id, nome, sigla) VALUES (DEFAULT, 1, 28, 'Rio de Janeiro','RJ');
INSERT INTO cgmbr.estado (id, version, pais_id, nome, sigla) VALUES (DEFAULT, 1, 28, 'São Paulo','SP');
INSERT INTO cgmbr.estado (id, version, pais_id, nome, sigla) VALUES (DEFAULT, 1, 28, 'Paraná','PR');
INSERT INTO cgmbr.estado (id, version, pais_id, nome, sigla) VALUES (DEFAULT, 1, 28, 'Santa Catarina','SC');
INSERT INTO cgmbr.estado (id, version, pais_id, nome, sigla) VALUES (DEFAULT, 1, 28, 'Rio Grande do Sul','RS');
INSERT INTO cgmbr.estado (id, version, pais_id, nome, sigla) VALUES (DEFAULT, 1, 28, 'Mato Grosso do Sul','MS');
INSERT INTO cgmbr.estado (id, version, pais_id, nome, sigla) VALUES (DEFAULT, 1, 28, 'Mato Grosso','MT');
INSERT INTO cgmbr.estado (id, version, pais_id, nome, sigla) VALUES (DEFAULT, 1, 28, 'Goiás','GO');
INSERT INTO cgmbr.estado (id, version, pais_id, nome, sigla) VALUES (DEFAULT, 1, 28, 'Distrito Federal','DF');

