import com.endereco.Endereco

import com.acesso.ShiroRole;
import com.acesso.ShiroUser;
import com.congregacao.Congregacao;
import com.endereco.Cidade;
import com.endereco.Endereco;
import com.endereco.Estado
import com.endereco.Pais;
import com.membro.Cargo;

import org.apache.shiro.crypto.hash.Sha256Hash

class BootStrap {

	def init = { servletContext ->

		/*Definição de usuário administrador*/
		def adminRole = ShiroRole.findByName("Administrador")

		if(!adminRole){
			adminRole = new ShiroRole(name: 'Administrador')
			adminRole.addToPermissions("*:*")
			adminRole.save()
		}

		def admin = ShiroUser.findByUsername('admin')

		if(!admin){
			admin = new ShiroUser(username: 'admin', passwordHash: new Sha256Hash('admin').toHex())
			admin.save()
			adminRole.addToUsers(admin)
			adminRole.save()
		}
		
		/*Definição de Pais*/
		Pais bra = Pais.findByNome(Pais.BRA) ?: new Pais(nome: Pais.BRA).save()
		Pais ptg = Pais.findByNome(Pais.PTG) ?: new Pais(nome: Pais.PTG).save() 
		
		/*Definição de Estados para BRA*/
		Estado ro = Estado.findBySigla("RO") ?: new Estado(pais: bra, nome: "Rondônia", sigla: "RO").save()
		Estado ac = Estado.findBySigla("AC") ?: new Estado(pais: bra, nome: "Acre", sigla: "AC").save()
		Estado am = Estado.findBySigla("AM") ?: new Estado(pais: bra, nome: "Amazonas", sigla: "AM").save()
		Estado rr = Estado.findBySigla("RR") ?: new Estado(pais: bra, nome: "Roraima", sigla: "RR").save()
		Estado pa = Estado.findBySigla("PA") ?: new Estado(pais: bra, nome: "Pará", sigla: "PA").save()
		Estado ap = Estado.findBySigla("AP") ?: new Estado(pais: bra, nome: "Amapá", sigla: "AP").save()
		Estado to = Estado.findBySigla("TO") ?: new Estado(pais: bra, nome: "Tocantins", sigla: "TO").save()
		Estado ma = Estado.findBySigla("MA") ?: new Estado(pais: bra, nome: "Maranhão", sigla: "MA").save()
		Estado pi = Estado.findBySigla("PI") ?: new Estado(pais: bra, nome: "Piauí", sigla: "PI").save()
		Estado ce = Estado.findBySigla("CE") ?: new Estado(pais: bra, nome: "Ceará", sigla: "CE").save()
		Estado rn = Estado.findBySigla("RN") ?: new Estado(pais: bra, nome: "Rio Grande do Norte", sigla: "RN").save()
		Estado pb = Estado.findBySigla("PB") ?: new Estado(pais: bra, nome: "Paraíba", sigla: "PB").save()
		Estado pe = Estado.findBySigla("PE") ?: new Estado(pais: bra, nome: "Pernambuco", sigla: "PE").save()
		Estado al = Estado.findBySigla("AL") ?: new Estado(pais: bra, nome: "Alagoas", sigla: "AL").save()
		Estado se = Estado.findBySigla("SE") ?: new Estado(pais: bra, nome: "Sergipe", sigla: "SE").save()
		Estado ba = Estado.findBySigla("BA") ?: new Estado(pais: bra, nome: "Bahia", sigla: "BA").save()
		Estado mg = Estado.findBySigla("MG") ?: new Estado(pais: bra, nome: "Minas Gerais", sigla: "MG").save()
		Estado es = Estado.findBySigla("ES") ?: new Estado(pais: bra, nome: "Espírito Santo", sigla: "ES").save()
		Estado rj = Estado.findBySigla("RJ") ?: new Estado(pais: bra, nome: "Rio de Janeiro", sigla: "RJ").save()
		Estado sp = Estado.findBySigla("SP") ?: new Estado(pais: bra, nome: "São Paulo", sigla: "SP").save()
		Estado pr = Estado.findBySigla("PR") ?: new Estado(pais: bra, nome: "Paraná", sigla: "PR").save()
		Estado sc = Estado.findBySigla("SC") ?: new Estado(pais: bra, nome: "Santa Catarina", sigla: "SC").save()
		Estado rs = Estado.findBySigla("RS") ?: new Estado(pais: bra, nome: "Rio Grande do Sul", sigla: "RS").save()
		Estado ms = Estado.findBySigla("MS") ?: new Estado(pais: bra, nome: "Mato Grosso do Sul", sigla: "MS").save()
		Estado mt = Estado.findBySigla("MT") ?: new Estado(pais: bra, nome: "Mato Grosso", sigla: "MT").save()
		Estado go = Estado.findBySigla("GO") ?: new Estado(pais: bra, nome: "Goiás", sigla: "GO").save()
		Estado df = Estado.findBySigla("DF") ?: new Estado(pais: bra, nome: "Distrito Federal", sigla: "DF").save()
		
		/*Definição de Cidades para PR*/
		Cidade mga = Cidade.findByNome("Maringá") ?: new Cidade(estado: pr, nome: "Maringá").save()
		/*
		Cidade.findByNome("Abatiá") ?: new Cidade(estado: pr, nome:"Abatiá").save()
		Cidade.findByNome("Adrianópolis") ?: new Cidade(estado: pr, nome:"Adrianópolis").save()
		Cidade.findByNome("Agudos do Sul") ?: new Cidade(estado: pr, nome:"Agudos do Sul").save()
		Cidade.findByNome("Almirante Tamandaré") ?: new Cidade(estado: pr, nome:"Almirante Tamandaré").save()
		Cidade.findByNome("Altamira do Paraná") ?: new Cidade(estado: pr, nome:"Altamira do Paraná").save()
		Cidade.findByNome("Altônia") ?: new Cidade(estado: pr, nome:"Altônia").save()
		Cidade.findByNome("Alto Paraná") ?: new Cidade(estado: pr, nome:"Alto Paraná").save()
		Cidade.findByNome("Alto Piquiri") ?: new Cidade(estado: pr, nome:"Alto Piquiri").save()
		Cidade.findByNome("Alvorada do Sul") ?: new Cidade(estado: pr, nome:"Alvorada do Sul").save()
		Cidade.findByNome("Amaporã") ?: new Cidade(estado: pr, nome:"Amaporã").save()
		Cidade.findByNome("Ampére") ?: new Cidade(estado: pr, nome:"Ampére").save()
		Cidade.findByNome("Anahy") ?: new Cidade(estado: pr, nome:"Anahy").save()
		Cidade.findByNome("Andirá") ?: new Cidade(estado: pr, nome:"Andirá").save()
		Cidade.findByNome("Ângulo") ?: new Cidade(estado: pr, nome:"Ângulo").save()
		Cidade.findByNome("Antonina") ?: new Cidade(estado: pr, nome:"Antonina").save()
		Cidade.findByNome("Antônio Olinto") ?: new Cidade(estado: pr, nome:"Antônio Olinto").save()
		Cidade.findByNome("Apucarana") ?: new Cidade(estado: pr, nome:"Apucarana").save()
		Cidade.findByNome("Arapongas") ?: new Cidade(estado: pr, nome:"Arapongas").save()
		Cidade.findByNome("Arapoti") ?: new Cidade(estado: pr, nome:"Arapoti").save()
		Cidade.findByNome("Arapuã") ?: new Cidade(estado: pr, nome:"Arapuã").save()
		Cidade.findByNome("Araruna") ?: new Cidade(estado: pr, nome:"Araruna").save()
		Cidade.findByNome("Araucária") ?: new Cidade(estado: pr, nome:"Araucária").save()
		Cidade.findByNome("Ariranha do Ivaí") ?: new Cidade(estado: pr, nome:"Ariranha do Ivaí").save()
		Cidade.findByNome("Assaí") ?: new Cidade(estado: pr, nome:"Assaí").save()
		Cidade.findByNome("Assis Chateaubriand") ?: new Cidade(estado: pr, nome:"Assis Chateaubriand").save()
		Cidade.findByNome("Astorga") ?: new Cidade(estado: pr, nome:"Astorga").save()
		Cidade.findByNome("Atalaia") ?: new Cidade(estado: pr, nome:"Atalaia").save()
		Cidade.findByNome("Balsa Nova") ?: new Cidade(estado: pr, nome:"Balsa Nova").save()
		Cidade.findByNome("Bandeirantes") ?: new Cidade(estado: pr, nome:"Bandeirantes").save()
		Cidade.findByNome("Barbosa Ferraz") ?: new Cidade(estado: pr, nome:"Barbosa Ferraz").save()
		Cidade.findByNome("Barracão") ?: new Cidade(estado: pr, nome: "Barracão").save()
		Cidade.findByNome("Barra do Jacaré") ?: new Cidade(estado: pr, nome: "Barra do Jacaré").save()
		Cidade.findByNome("Bela Vista da Caroba") ?: new Cidade(estado: pr, nome: "Bela Vista da Caroba").save()
		Cidade.findByNome("Bela Vista do Paraíso") ?: new Cidade(estado: pr, nome: "Bela Vista do Paraíso").save()
		Cidade.findByNome("Bituruna") ?: new Cidade(estado: pr, nome: "Bituruna").save()
		Cidade.findByNome("Boa Esperança") ?: new Cidade(estado: pr, nome: "Boa Esperança").save()
		Cidade.findByNome("Boa Esperança do Iguaçu") ?: new Cidade(estado: pr, nome: "Boa Esperança do Iguaçu").save()
		Cidade.findByNome("Boa Ventura de São Roque") ?: new Cidade(estado: pr, nome: "Boa Ventura de São Roque").save()
		Cidade.findByNome("Boa Vista da Aparecida") ?: new Cidade(estado: pr, nome: "Boa Vista da Aparecida").save()
		Cidade.findByNome("Bocaiúva do Sul") ?: new Cidade(estado: pr, nome: "Bocaiúva do Sul").save()
		Cidade.findByNome("Bom Jesus do Sul") ?: new Cidade(estado: pr, nome: "Bom Jesus do Sul").save()
		Cidade.findByNome("Bom Sucesso") ?: new Cidade(estado: pr, nome: "Bom Sucesso").save()
		Cidade.findByNome("Bom Sucesso do Sul") ?: new Cidade(estado: pr, nome: "Bom Sucesso do Sul").save()
		Cidade.findByNome("Borrazópolis") ?: new Cidade(estado: pr, nome: "Borrazópolis").save()
		Cidade.findByNome("Braganey") ?: new Cidade(estado: pr, nome: "Braganey").save()
		Cidade.findByNome("Brasilândia do Sul") ?: new Cidade(estado: pr, nome: "Brasilândia do Sul").save()
		Cidade.findByNome("Cafeara") ?: new Cidade(estado: pr, nome: "Cafeara").save()
		Cidade.findByNome("Cafelândia") ?: new Cidade(estado: pr, nome: "Cafelândia").save()
		Cidade.findByNome("Cafezal do Sul") ?: new Cidade(estado: pr, nome: "Cafezal do Sul").save()
		Cidade.findByNome("Califórnia") ?: new Cidade(estado: pr, nome: "Califórnia").save()
		Cidade.findByNome("Cambará") ?: new Cidade(estado: pr, nome: "Cambará").save()
		Cidade.findByNome("Cambé") ?: new Cidade(estado: pr, nome: "Cambé").save()
		Cidade.findByNome("Cambira") ?: new Cidade(estado: pr, nome: "Cambira").save()
		Cidade.findByNome("Campina da Lagoa") ?: new Cidade(estado: pr, nome: "Campina da Lagoa").save()
		Cidade.findByNome("Campina do Simão") ?: new Cidade(estado: pr, nome: "Campina do Simão").save()
		Cidade.findByNome("Campina Grande do Sul") ?: new Cidade(estado: pr, nome: "Campina Grande do Sul").save()
		Cidade.findByNome("Campo Bonito") ?: new Cidade(estado: pr, nome: "Campo Bonito").save()
		Cidade.findByNome("Campo do Tenente") ?: new Cidade(estado: pr, nome: "Campo do Tenente").save()
		Cidade.findByNome("Campo Largo") ?: new Cidade(estado: pr, nome: "Campo Largo").save()
		Cidade.findByNome("Campo Magro") ?: new Cidade(estado: pr, nome: "Campo Magro").save()
		Cidade.findByNome("Campo Mourão") ?: new Cidade(estado: pr, nome: "Campo Mourão").save()
		Cidade.findByNome("Cândido de Abreu") ?: new Cidade(estado: pr, nome: "Cândido de Abreu").save()
		Cidade.findByNome("Candói") ?: new Cidade(estado: pr, nome: "Candói").save()
		Cidade.findByNome("Cantagalo") ?: new Cidade(estado: pr, nome: "Cantagalo").save()
		Cidade.findByNome("Capanema") ?: new Cidade(estado: pr, nome: "Capanema").save()
		Cidade.findByNome("Capitão Leônidas Marques") ?: new Cidade(estado: pr, nome: "Capitão Leônidas Marques").save()
		Cidade.findByNome("Carambeí") ?: new Cidade(estado: pr, nome: "Carambeí").save()
		Cidade.findByNome("Carlópolis") ?: new Cidade(estado: pr, nome: "Carlópolis").save()
		Cidade.findByNome("Cascavel") ?: new Cidade(estado: pr, nome: "Cascavel").save()
		Cidade.findByNome("Castro") ?: new Cidade(estado: pr, nome: "Castro").save()
		Cidade.findByNome("Catanduvas") ?: new Cidade(estado: pr, nome: "Catanduvas").save()
		Cidade.findByNome("Centenário do Sul") ?: new Cidade(estado: pr, nome: "Centenário do Sul").save()
		Cidade.findByNome("Cerro Azul") ?: new Cidade(estado: pr, nome: "Cerro Azul").save()
		Cidade.findByNome("Céu Azul") ?: new Cidade(estado: pr, nome: "Céu Azul").save()
		Cidade.findByNome("Chopinzinho") ?: new Cidade(estado: pr, nome: "Chopinzinho").save()
		Cidade.findByNome("Cianorte") ?: new Cidade(estado: pr, nome: "Cianorte").save()
		Cidade.findByNome("Cidade Gaúcha") ?: new Cidade(estado: pr, nome: "Cidade Gaúcha").save()
		Cidade.findByNome("Clevelândia") ?: new Cidade(estado: pr, nome: "Clevelândia").save()
		Cidade.findByNome("Colombo") ?: new Cidade(estado: pr, nome: "Colombo").save()
		Cidade.findByNome("Colorado") ?: new Cidade(estado: pr, nome: "Colorado").save()
		Cidade.findByNome("Congonhinhas") ?: new Cidade(estado: pr, nome: "Congonhinhas").save()
		Cidade.findByNome("Conselheiro Mairinck") ?: new Cidade(estado: pr, nome: "Conselheiro Mairinck").save()
		Cidade.findByNome("Contenda") ?: new Cidade(estado: pr, nome: "Contenda").save()
		Cidade.findByNome("Corbélia") ?: new Cidade(estado: pr, nome: "Corbélia").save()
		Cidade.findByNome("Cornélio Procópio") ?: new Cidade(estado: pr, nome: "Cornélio Procópio").save()
		Cidade.findByNome("Coronel Domingos Soares") ?: new Cidade(estado: pr, nome: "Coronel Domingos Soares").save()
		Cidade.findByNome("Coronel Vivida") ?: new Cidade(estado: pr, nome: "Coronel Vivida").save()
		Cidade.findByNome("Corumbataí do Sul") ?: new Cidade(estado: pr, nome: "Corumbataí do Sul").save()
		Cidade.findByNome("Cruzeiro do Iguaçu") ?: new Cidade(estado: pr, nome: "Cruzeiro do Iguaçu").save()
		Cidade.findByNome("Cruzeiro do Oeste") ?: new Cidade(estado: pr, nome: "Cruzeiro do Oeste").save()
		Cidade.findByNome("Cruzeiro do Sul") ?: new Cidade(estado: pr, nome: "Cruzeiro do Sul").save()
		Cidade.findByNome("Cruz Machado") ?: new Cidade(estado: pr, nome: "Cruz Machado").save()
		Cidade.findByNome("Cruzmaltina") ?: new Cidade(estado: pr, nome: "Cruzmaltina").save()
		Cidade.findByNome("Curitiba") ?: new Cidade(estado: pr, nome: "Curitiba").save()
		Cidade.findByNome("Curiúva") ?: new Cidade(estado: pr, nome: "Curiúva").save()
		Cidade.findByNome("Diamante do Norte") ?: new Cidade(estado: pr, nome: "Diamante do Norte").save()
		Cidade.findByNome("Diamante do Sul") ?: new Cidade(estado: pr, nome: "Diamante do Sul").save()
		Cidade.findByNome("Diamante D''Oeste") ?: new Cidade(estado: pr, nome: "Diamante D''Oeste").save()
		Cidade.findByNome("Dois Vizinhos") ?: new Cidade(estado: pr, nome: "Dois Vizinhos").save()
		Cidade.findByNome("Douradina") ?: new Cidade(estado: pr, nome: "Douradina").save()
		Cidade.findByNome("Doutor Camargo") ?: new Cidade(estado: pr, nome: "Doutor Camargo").save()
		Cidade.findByNome("Enéas Marques") ?: new Cidade(estado: pr, nome: "Enéas Marques").save()
		Cidade.findByNome("Engenheiro Beltrão") ?: new Cidade(estado: pr, nome: "Engenheiro Beltrão").save()
		Cidade.findByNome("Esperança Nova") ?: new Cidade(estado: pr, nome: "Esperança Nova").save()
		Cidade.findByNome("Entre Rios do Oeste") ?: new Cidade(estado: pr, nome: "Entre Rios do Oeste").save()
		Cidade.findByNome("Espigão Alto do Iguaçu") ?: new Cidade(estado: pr, nome: "Espigão Alto do Iguaçu").save()
		Cidade.findByNome("Farol") ?: new Cidade(estado: pr, nome: "Farol").save()
		Cidade.findByNome("Faxinal") ?: new Cidade(estado: pr, nome: "Faxinal").save()
		Cidade.findByNome("Fazenda Rio Grande") ?: new Cidade(estado: pr, nome: "Fazenda Rio Grande").save()
		Cidade.findByNome("Fênix") ?: new Cidade(estado: pr, nome: "Fênix").save()
		Cidade.findByNome("Fernandes Pinheiro") ?: new Cidade(estado: pr, nome: "Fernandes Pinheiro").save()
		Cidade.findByNome("Figueira") ?: new Cidade(estado: pr, nome: "Figueira").save()
		Cidade.findByNome("Floraí") ?: new Cidade(estado: pr, nome: "Floraí").save()
		Cidade.findByNome("Flor da Serra do Sul") ?: new Cidade(estado: pr, nome: "Flor da Serra do Sul").save()
		Cidade.findByNome("Floresta") ?: new Cidade(estado: pr, nome: "Floresta").save()
		Cidade.findByNome("Florestópolis") ?: new Cidade(estado: pr, nome: "Florestópolis").save()
		Cidade.findByNome("Flórida") ?: new Cidade(estado: pr, nome: "Flórida").save()
		Cidade.findByNome("Formosa do Oeste") ?: new Cidade(estado: pr, nome: "Formosa do Oeste").save()
		Cidade.findByNome("Foz do Iguaçu") ?: new Cidade(estado: pr, nome: "Foz do Iguaçu").save()
		Cidade.findByNome("Francisco Alves") ?: new Cidade(estado: pr, nome: "Francisco Alves").save()
		Cidade.findByNome("Francisco Beltrão") ?: new Cidade(estado: pr, nome: "Francisco Beltrão").save()
		Cidade.findByNome("Foz do Jordão") ?: new Cidade(estado: pr, nome: "Foz do Jordão").save()
		Cidade.findByNome("General Carneiro") ?: new Cidade(estado: pr, nome: "General Carneiro").save()
		Cidade.findByNome("Godoy Moreira") ?: new Cidade(estado: pr, nome: "Godoy Moreira").save()
		Cidade.findByNome("Goioerê") ?: new Cidade(estado: pr, nome: "Goioerê").save()
		Cidade.findByNome("Goioxim") ?: new Cidade(estado: pr, nome: "Goioxim").save()
		Cidade.findByNome("Grandes Rios") ?: new Cidade(estado: pr, nome: "Grandes Rios").save()
		Cidade.findByNome("Guaíra") ?: new Cidade(estado: pr, nome: "Guaíra").save()
		Cidade.findByNome("Guairaçá") ?: new Cidade(estado: pr, nome: "Guairaçá").save()
		Cidade.findByNome("Guamiranga") ?: new Cidade(estado: pr, nome: "Guamiranga").save()
		Cidade.findByNome("Guapirama") ?: new Cidade(estado: pr, nome: "Guapirama").save()
		Cidade.findByNome("Guaporema") ?: new Cidade(estado: pr, nome: "Guaporema").save()
		Cidade.findByNome("Guaraci") ?: new Cidade(estado: pr, nome: "Guaraci").save()
		Cidade.findByNome("Guaraniaçu") ?: new Cidade(estado: pr, nome: "Guaraniaçu").save()
		Cidade.findByNome("Guarapuava") ?: new Cidade(estado: pr, nome: "Guarapuava").save()
		Cidade.findByNome("Guaraqueçaba") ?: new Cidade(estado: pr, nome: "Guaraqueçaba").save()
		Cidade.findByNome("Guaratuba") ?: new Cidade(estado: pr, nome: "Guaratuba").save()
		Cidade.findByNome("Honório Serpa") ?: new Cidade(estado: pr, nome: "Honório Serpa").save()
		Cidade.findByNome("Ibaiti") ?: new Cidade(estado: pr, nome: "Ibaiti").save()
		Cidade.findByNome("Ibema") ?: new Cidade(estado: pr, nome: "Ibema").save()
		Cidade.findByNome("Ibiporã") ?: new Cidade(estado: pr, nome: "Ibiporã").save()
		Cidade.findByNome("Icaraíma") ?: new Cidade(estado: pr, nome: "Icaraíma").save()
		Cidade.findByNome("Iguaraçu") ?: new Cidade(estado: pr, nome: "Iguaraçu").save()
		Cidade.findByNome("Iguatu") ?: new Cidade(estado: pr, nome: "Iguatu").save()
		Cidade.findByNome("Imbaú") ?: new Cidade(estado: pr, nome: "Imbaú").save()
		Cidade.findByNome("Imbituva") ?: new Cidade(estado: pr, nome: "Imbituva").save()
		Cidade.findByNome("Inácio Martins") ?: new Cidade(estado: pr, nome: "Inácio Martins").save()
		Cidade.findByNome("Inajá") ?: new Cidade(estado: pr, nome: "Inajá").save()
		Cidade.findByNome("Indianópolis") ?: new Cidade(estado: pr, nome: "Indianópolis").save()
		Cidade.findByNome("Ipiranga") ?: new Cidade(estado: pr, nome: "Ipiranga").save()
		Cidade.findByNome("Iporã") ?: new Cidade(estado: pr, nome: "Iporã").save()
		Cidade.findByNome("Iracema do Oeste") ?: new Cidade(estado: pr, nome: "Iracema do Oeste").save()
		Cidade.findByNome("Irati") ?: new Cidade(estado: pr, nome: "Irati").save()
		Cidade.findByNome("Iretama") ?: new Cidade(estado: pr, nome: "Iretama").save()
		Cidade.findByNome("Itaguajé") ?: new Cidade(estado: pr, nome: "Itaguajé").save()
		Cidade.findByNome("Itaipulândia") ?: new Cidade(estado: pr, nome: "Itaipulândia").save()
		Cidade.findByNome("Itambaracá") ?: new Cidade(estado: pr, nome: "Itambaracá").save()
		Cidade.findByNome("Itambé") ?: new Cidade(estado: pr, nome: "Itambé").save()
		Cidade.findByNome("Itapejara d''Oeste") ?: new Cidade(estado: pr, nome: "Itapejara d''Oeste").save()
		Cidade.findByNome("Itaperuçu") ?: new Cidade(estado: pr, nome: "Itaperuçu").save()
		Cidade.findByNome("Itaúna do Sul") ?: new Cidade(estado: pr, nome: "Itaúna do Sul").save()
		Cidade.findByNome("Ivaí") ?: new Cidade(estado: pr, nome: "Ivaí").save()
		Cidade.findByNome("Ivaiporã") ?: new Cidade(estado: pr, nome: "Ivaiporã").save()
		Cidade.findByNome("Ivaté") ?: new Cidade(estado: pr, nome: "Ivaté").save()
		Cidade.findByNome("Ivatuba") ?: new Cidade(estado: pr, nome: "Ivatuba").save()
		Cidade.findByNome("Jaboti") ?: new Cidade(estado: pr, nome: "Jaboti").save()
		Cidade.findByNome("Jacarezinho") ?: new Cidade(estado: pr, nome: "Jacarezinho").save()
		Cidade.findByNome("Jaguapitã") ?: new Cidade(estado: pr, nome: "Jaguapitã").save()
		Cidade.findByNome("Jaguariaíva") ?: new Cidade(estado: pr, nome: "Jaguariaíva").save()
		Cidade.findByNome("Jandaia do Sul") ?: new Cidade(estado: pr, nome: "Jandaia do Sul").save()
		Cidade.findByNome("Janiópolis") ?: new Cidade(estado: pr, nome: "Janiópolis").save()
		Cidade.findByNome("Japira") ?: new Cidade(estado: pr, nome: "Japira").save()
		Cidade.findByNome("Japurá") ?: new Cidade(estado: pr, nome: "Japurá").save()
		Cidade.findByNome("Jardim Alegre") ?: new Cidade(estado: pr, nome: "Jardim Alegre").save()
		Cidade.findByNome("Jardim Olinda") ?: new Cidade(estado: pr, nome: "Jardim Olinda").save()
		Cidade.findByNome("Jataizinho") ?: new Cidade(estado: pr, nome: "Jataizinho").save()
		Cidade.findByNome("Jesuítas") ?: new Cidade(estado: pr, nome: "Jesuítas").save()
		Cidade.findByNome("Joaquim Távora") ?: new Cidade(estado: pr, nome: "Joaquim Távora").save()
		Cidade.findByNome("Jundiaí do Sul") ?: new Cidade(estado: pr, nome: "Jundiaí do Sul").save()
		Cidade.findByNome("Juranda") ?: new Cidade(estado: pr, nome: "Juranda").save()
		Cidade.findByNome("Jussara") ?: new Cidade(estado: pr, nome: "Jussara").save()
		Cidade.findByNome("Kaloré") ?: new Cidade(estado: pr, nome: "Kaloré").save()
		Cidade.findByNome("Lapa") ?: new Cidade(estado: pr, nome: "Lapa").save()
		Cidade.findByNome("Laranjal") ?: new Cidade(estado: pr, nome: "Laranjal").save()
		Cidade.findByNome("Laranjeiras do Sul") ?: new Cidade(estado: pr, nome: "Laranjeiras do Sul").save()
		Cidade.findByNome("Leópolis") ?: new Cidade(estado: pr, nome: "Leópolis").save()
		Cidade.findByNome("Lidianópolis") ?: new Cidade(estado: pr, nome: "Lidianópolis").save()
		Cidade.findByNome("Lindoeste") ?: new Cidade(estado: pr, nome: "Lindoeste").save()
		Cidade.findByNome("Loanda") ?: new Cidade(estado: pr, nome: "Loanda").save()
		Cidade.findByNome("Lobato") ?: new Cidade(estado: pr, nome: "Lobato").save()
		Cidade.findByNome("Londrina") ?: new Cidade(estado: pr, nome: "Londrina").save()
		Cidade.findByNome("Luiziana") ?: new Cidade(estado: pr, nome: "Luiziana").save()
		Cidade.findByNome("Lunardelli") ?: new Cidade(estado: pr, nome: "Lunardelli").save()
		Cidade.findByNome("Lupionópolis") ?: new Cidade(estado: pr, nome: "Lupionópolis").save()
		Cidade.findByNome("Mallet") ?: new Cidade(estado: pr, nome: "Mallet").save()
		Cidade.findByNome("Mamborê") ?: new Cidade(estado: pr, nome: "Mamborê").save()
		Cidade.findByNome("Mandaguaçu") ?: new Cidade(estado: pr, nome: "Mandaguaçu").save()
		Cidade.findByNome("Mandaguari") ?: new Cidade(estado: pr, nome: "Mandaguari").save()
		Cidade.findByNome("Mandirituba") ?: new Cidade(estado: pr, nome: "Mandirituba").save()
		Cidade.findByNome("Manfrinópolis") ?: new Cidade(estado: pr, nome: "Manfrinópolis").save()
		Cidade.findByNome("Mangueirinha") ?: new Cidade(estado: pr, nome: "Mangueirinha").save()
		Cidade.findByNome("Manoel Ribas") ?: new Cidade(estado: pr, nome: "Manoel Ribas").save()
		Cidade.findByNome("Marechal Cândido Rondon") ?: new Cidade(estado: pr, nome: "Marechal Cândido Rondon").save()
		Cidade.findByNome("Maria Helena") ?: new Cidade(estado: pr, nome: "Maria Helena").save()
		Cidade.findByNome("Marialva") ?: new Cidade(estado: pr, nome: "Marialva").save()
		Cidade.findByNome("Marilândia do Sul") ?: new Cidade(estado: pr, nome: "Marilândia do Sul").save()
		Cidade.findByNome("Marilena") ?: new Cidade(estado: pr, nome: "Marilena").save()
		Cidade.findByNome("Mariluz") ?: new Cidade(estado: pr, nome: "Mariluz").save()
		Cidade.findByNome("Maringá") ?: new Cidade(estado: pr, nome: "Maringá").save()
		Cidade.findByNome("Mariópolis") ?: new Cidade(estado: pr, nome: "Mariópolis").save()
		Cidade.findByNome("Maripá") ?: new Cidade(estado: pr, nome: "Maripá").save()
		Cidade.findByNome("Marmeleiro") ?: new Cidade(estado: pr, nome: "Marmeleiro").save()
		Cidade.findByNome("Marquinho") ?: new Cidade(estado: pr, nome: "Marquinho").save()
		Cidade.findByNome("Marumbi") ?: new Cidade(estado: pr, nome: "Marumbi").save()
		Cidade.findByNome("Matelândia") ?: new Cidade(estado: pr, nome: "Matelândia").save()
		Cidade.findByNome("Matinhos") ?: new Cidade(estado: pr, nome: "Matinhos").save()
		Cidade.findByNome("Mato Rico") ?: new Cidade(estado: pr, nome: "Mato Rico").save()
		Cidade.findByNome("Mauá da Serra") ?: new Cidade(estado: pr, nome: "Mauá da Serra").save()
		Cidade.findByNome("Medianeira") ?: new Cidade(estado: pr, nome: "Medianeira").save()
		Cidade.findByNome("Mercedes") ?: new Cidade(estado: pr, nome: "Mercedes").save()
		Cidade.findByNome("Mirador") ?: new Cidade(estado: pr, nome: "Mirador").save()
		Cidade.findByNome("Miraselva") ?: new Cidade(estado: pr, nome: "Miraselva").save()
		Cidade.findByNome("Missal") ?: new Cidade(estado: pr, nome: "Missal").save()
		Cidade.findByNome("Moreira Sales") ?: new Cidade(estado: pr, nome: "Moreira Sales").save()
		Cidade.findByNome("Morretes") ?: new Cidade(estado: pr, nome: "Morretes").save()
		Cidade.findByNome("Munhoz de Melo") ?: new Cidade(estado: pr, nome: "Munhoz de Melo").save()
		Cidade.findByNome("Nossa Senhora das Graças") ?: new Cidade(estado: pr, nome: "Nossa Senhora das Graças").save()
		Cidade.findByNome("Nova Aliança do Ivaí") ?: new Cidade(estado: pr, nome: "Nova Aliança do Ivaí").save()
		Cidade.findByNome("Nova América da Colina") ?: new Cidade(estado: pr, nome: "Nova América da Colina").save()
		Cidade.findByNome("Nova Aurora") ?: new Cidade(estado: pr, nome: "Nova Aurora").save()
		Cidade.findByNome("Nova Cantu") ?: new Cidade(estado: pr, nome: "Nova Cantu").save()
		Cidade.findByNome("Nova Esperança") ?: new Cidade(estado: pr, nome: "Nova Esperança").save()
		Cidade.findByNome("Nova Esperança do Sudoeste") ?: new Cidade(estado: pr, nome: "Nova Esperança do Sudoeste").save()
		Cidade.findByNome("Nova Fátima") ?: new Cidade(estado: pr, nome: "Nova Fátima").save()
		Cidade.findByNome("Nova Laranjeiras") ?: new Cidade(estado: pr, nome: "Nova Laranjeiras").save()
		Cidade.findByNome("Nova Londrina") ?: new Cidade(estado: pr, nome: "Nova Londrina").save()
		Cidade.findByNome("Nova Olímpia") ?: new Cidade(estado: pr, nome: "Nova Olímpia").save()
		Cidade.findByNome("Nova Santa Bárbara") ?: new Cidade(estado: pr, nome: "Nova Santa Bárbara").save()
		Cidade.findByNome("Nova Santa Rosa") ?: new Cidade(estado: pr, nome: "Nova Santa Rosa").save()
		Cidade.findByNome("Nova Prata do Iguaçu") ?: new Cidade(estado: pr, nome: "Nova Prata do Iguaçu").save()
		Cidade.findByNome("Nova Tebas") ?: new Cidade(estado: pr, nome: "Nova Tebas").save()
		Cidade.findByNome("Novo Itacolomi") ?: new Cidade(estado: pr, nome: "Novo Itacolomi").save()
		Cidade.findByNome("Ortigueira") ?: new Cidade(estado: pr, nome: "Ortigueira").save()
		Cidade.findByNome("Ourizona") ?: new Cidade(estado: pr, nome: "Ourizona").save()
		Cidade.findByNome("Ouro Verde do Oeste") ?: new Cidade(estado: pr, nome: "Ouro Verde do Oeste").save()
		Cidade.findByNome("Paiçandu") ?: new Cidade(estado: pr, nome: "Paiçandu").save()
		Cidade.findByNome("Palmas") ?: new Cidade(estado: pr, nome: "Palmas").save()
		Cidade.findByNome("Palmeira") ?: new Cidade(estado: pr, nome: "Palmeira").save()
		Cidade.findByNome("Palmital") ?: new Cidade(estado: pr, nome: "Palmital").save()
		Cidade.findByNome("Palotina") ?: new Cidade(estado: pr, nome: "Palotina").save()
		Cidade.findByNome("Paraíso do Norte") ?: new Cidade(estado: pr, nome: "Paraíso do Norte").save()
		Cidade.findByNome("Paranacity") ?: new Cidade(estado: pr, nome: "Paranacity").save()
		Cidade.findByNome("Paranaguá") ?: new Cidade(estado: pr, nome: "Paranaguá").save()
		Cidade.findByNome("Paranapoema") ?: new Cidade(estado: pr, nome: "Paranapoema").save()
		Cidade.findByNome("Paranavaí") ?: new Cidade(estado: pr, nome: "Paranavaí").save()
		Cidade.findByNome("Pato Bragado") ?: new Cidade(estado: pr, nome: "Pato Bragado").save()
		Cidade.findByNome("Pato Branco") ?: new Cidade(estado: pr, nome: "Pato Branco").save()
		Cidade.findByNome("Paula Freitas") ?: new Cidade(estado: pr, nome: "Paula Freitas").save()
		Cidade.findByNome("Paulo Frontin") ?: new Cidade(estado: pr, nome: "Paulo Frontin").save()
		Cidade.findByNome("Peabiru") ?: new Cidade(estado: pr, nome: "Peabiru").save()
		Cidade.findByNome("Perobal") ?: new Cidade(estado: pr, nome: "Perobal").save()
		Cidade.findByNome("Pérola") ?: new Cidade(estado: pr, nome: "Pérola").save()
		Cidade.findByNome("Pérola d''Oeste") ?: new Cidade(estado: pr, nome: "Pérola d''Oeste").save()
		Cidade.findByNome("Piên") ?: new Cidade(estado: pr, nome: "Piên").save()
		Cidade.findByNome("Pinhais") ?: new Cidade(estado: pr, nome: "Pinhais").save()
		Cidade.findByNome("Pinhalão") ?: new Cidade(estado: pr, nome: "Pinhalão").save()
		Cidade.findByNome("Pinhal de São Bento") ?: new Cidade(estado: pr, nome: "Pinhal de São Bento").save()
		Cidade.findByNome("Pinhão") ?: new Cidade(estado: pr, nome: "Pinhão").save()
		Cidade.findByNome("Piraí do Sul") ?: new Cidade(estado: pr, nome: "Piraí do Sul").save()
		Cidade.findByNome("Piraquara") ?: new Cidade(estado: pr, nome: "Piraquara").save()
		Cidade.findByNome("Pitanga") ?: new Cidade(estado: pr, nome: "Pitanga").save()
		Cidade.findByNome("Pitangueiras") ?: new Cidade(estado: pr, nome: "Pitangueiras").save()
		Cidade.findByNome("Planaltina do Paraná") ?: new Cidade(estado: pr, nome: "Planaltina do Paraná").save()
		Cidade.findByNome("Planalto") ?: new Cidade(estado: pr, nome: "Planalto").save()
		Cidade.findByNome("Ponta Grossa") ?: new Cidade(estado: pr, nome: "Ponta Grossa").save()
		Cidade.findByNome("Pontal do Paraná") ?: new Cidade(estado: pr, nome: "Pontal do Paraná").save()
		Cidade.findByNome("Porecatu") ?: new Cidade(estado: pr, nome: "Porecatu").save()
		Cidade.findByNome("Porto Amazonas") ?: new Cidade(estado: pr, nome: "Porto Amazonas").save()
		Cidade.findByNome("Porto Barreiro") ?: new Cidade(estado: pr, nome: "Porto Barreiro").save()
		Cidade.findByNome("Porto Rico") ?: new Cidade(estado: pr, nome: "Porto Rico").save()
		Cidade.findByNome("Porto Vitória") ?: new Cidade(estado: pr, nome: "Porto Vitória").save()
		Cidade.findByNome("Prado Ferreira") ?: new Cidade(estado: pr, nome: "Prado Ferreira").save()
		Cidade.findByNome("Pranchita") ?: new Cidade(estado: pr, nome: "Pranchita").save()
		Cidade.findByNome("Presidente Castelo Branco") ?: new Cidade(estado: pr, nome: "Presidente Castelo Branco").save()
		Cidade.findByNome("Primeiro de Maio") ?: new Cidade(estado: pr, nome: "Primeiro de Maio").save()
		Cidade.findByNome("Prudentópolis") ?: new Cidade(estado: pr, nome: "Prudentópolis").save()
		Cidade.findByNome("Quarto Centenário") ?: new Cidade(estado: pr, nome: "Quarto Centenário").save()
		Cidade.findByNome("Quatiguá") ?: new Cidade(estado: pr, nome: "Quatiguá").save()
		Cidade.findByNome("Quatro Barras") ?: new Cidade(estado: pr, nome: "Quatro Barras").save()
		Cidade.findByNome("Quatro Pontes") ?: new Cidade(estado: pr, nome: "Quatro Pontes").save()
		Cidade.findByNome("Quedas do Iguaçu") ?: new Cidade(estado: pr, nome: "Quedas do Iguaçu").save()
		Cidade.findByNome("Querência do Norte") ?: new Cidade(estado: pr, nome: "Querência do Norte").save()
		Cidade.findByNome("Quinta do Sol") ?: new Cidade(estado: pr, nome: "Quinta do Sol").save()
		Cidade.findByNome("Quitandinha") ?: new Cidade(estado: pr, nome: "Quitandinha").save()
		Cidade.findByNome("Ramilândia") ?: new Cidade(estado: pr, nome: "Ramilândia").save()
		Cidade.findByNome("Rancho Alegre") ?: new Cidade(estado: pr, nome: "Rancho Alegre").save()
		Cidade.findByNome("Rancho Alegre D''Oeste") ?: new Cidade(estado: pr, nome: "Rancho Alegre D''Oeste").save()
		Cidade.findByNome("Realeza") ?: new Cidade(estado: pr, nome: "Realeza").save()
		Cidade.findByNome("Rebouças") ?: new Cidade(estado: pr, nome: "Rebouças").save()
		Cidade.findByNome("Renascença") ?: new Cidade(estado: pr, nome: "Renascença").save()
		Cidade.findByNome("Reserva") ?: new Cidade(estado: pr, nome: "Reserva").save()
		Cidade.findByNome("Reserva do Iguaçu") ?: new Cidade(estado: pr, nome: "Reserva do Iguaçu").save()
		Cidade.findByNome("Ribeirão Claro") ?: new Cidade(estado: pr, nome: "Ribeirão Claro").save()
		Cidade.findByNome("Ribeirão do Pinhal") ?: new Cidade(estado: pr, nome: "Ribeirão do Pinhal").save()
		Cidade.findByNome("Rio Azul") ?: new Cidade(estado: pr, nome: "Rio Azul").save()
		Cidade.findByNome("Rio Bom") ?: new Cidade(estado: pr, nome: "Rio Bom").save()
		Cidade.findByNome("Rio Bonito do Iguaçu") ?: new Cidade(estado: pr, nome: "Rio Bonito do Iguaçu").save()
		Cidade.findByNome("Rio Branco do Ivaí") ?: new Cidade(estado: pr, nome: "Rio Branco do Ivaí").save()
		Cidade.findByNome("Rio Branco do Sul") ?: new Cidade(estado: pr, nome: "Rio Branco do Sul").save()
		Cidade.findByNome("Rio Negro") ?: new Cidade(estado: pr, nome: "Rio Negro").save()
		Cidade.findByNome("Rolândia") ?: new Cidade(estado: pr, nome: "Rolândia").save()
		Cidade.findByNome("Roncador") ?: new Cidade(estado: pr, nome: "Roncador").save()
		Cidade.findByNome("Rondon") ?: new Cidade(estado: pr, nome: "Rondon").save()
		Cidade.findByNome("Rosário do Ivaí") ?: new Cidade(estado: pr, nome: "Rosário do Ivaí").save()
		Cidade.findByNome("Sabáudia") ?: new Cidade(estado: pr, nome: "Sabáudia").save()
		Cidade.findByNome("Salgado Filho") ?: new Cidade(estado: pr, nome: "Salgado Filho").save()
		Cidade.findByNome("Salto do Itararé") ?: new Cidade(estado: pr, nome: "Salto do Itararé").save()
		Cidade.findByNome("Salto do Lontra") ?: new Cidade(estado: pr, nome: "Salto do Lontra").save()
		Cidade.findByNome("Santa Amélia") ?: new Cidade(estado: pr, nome: "Santa Amélia").save()
		Cidade.findByNome("Santa Cecília do Pavão") ?: new Cidade(estado: pr, nome: "Santa Cecília do Pavão").save()
		Cidade.findByNome("Santa Cruz de Monte Castelo") ?: new Cidade(estado: pr, nome: "Santa Cruz de Monte Castelo").save()
		Cidade.findByNome("Santa Fé") ?: new Cidade(estado: pr, nome: "Santa Fé").save()
		Cidade.findByNome("Santa Helena") ?: new Cidade(estado: pr, nome: "Santa Helena").save()
		Cidade.findByNome("Santa Inês") ?: new Cidade(estado: pr, nome: "Santa Inês").save()
		Cidade.findByNome("Santa Isabel do Ivaí") ?: new Cidade(estado: pr, nome: "Santa Isabel do Ivaí").save()
		Cidade.findByNome("Santa Izabel do Oeste") ?: new Cidade(estado: pr, nome: "Santa Izabel do Oeste").save()
		Cidade.findByNome("Santa Lúcia") ?: new Cidade(estado: pr, nome: "Santa Lúcia").save()
		Cidade.findByNome("Santa Maria do Oeste") ?: new Cidade(estado: pr, nome: "Santa Maria do Oeste").save()
		Cidade.findByNome("Santa Mariana") ?: new Cidade(estado: pr, nome: "Santa Mariana").save()
		Cidade.findByNome("Santa Mônica") ?: new Cidade(estado: pr, nome: "Santa Mônica").save()
		Cidade.findByNome("Santana do Itararé") ?: new Cidade(estado: pr, nome: "Santana do Itararé").save()
		Cidade.findByNome("Santa Tereza do Oeste") ?: new Cidade(estado: pr, nome: "Santa Tereza do Oeste").save()
		Cidade.findByNome("Santa Terezinha de Itaipu") ?: new Cidade(estado: pr, nome: "Santa Terezinha de Itaipu").save()
		Cidade.findByNome("Santo Antônio da Platina") ?: new Cidade(estado: pr, nome: "Santo Antônio da Platina").save()
		Cidade.findByNome("Santo Antônio do Caiuá") ?: new Cidade(estado: pr, nome: "Santo Antônio do Caiuá").save()
		Cidade.findByNome("Santo Antônio do Paraíso") ?: new Cidade(estado: pr, nome: "Santo Antônio do Paraíso").save()
		Cidade.findByNome("Santo Antônio do Sudoeste") ?: new Cidade(estado: pr, nome: "Santo Antônio do Sudoeste").save()
		Cidade.findByNome("Santo Inácio") ?: new Cidade(estado: pr, nome: "Santo Inácio").save()
		Cidade.findByNome("São Carlos do Ivaí") ?: new Cidade(estado: pr, nome: "São Carlos do Ivaí").save()
		Cidade.findByNome("São Jerônimo da Serra") ?: new Cidade(estado: pr, nome: "São Jerônimo da Serra").save()
		Cidade.findByNome("São João") ?: new Cidade(estado: pr, nome: "São João").save()
		Cidade.findByNome("São João do Caiuá") ?: new Cidade(estado: pr, nome: "São João do Caiuá").save()
		Cidade.findByNome("São João do Ivaí") ?: new Cidade(estado: pr, nome: "São João do Ivaí").save()
		Cidade.findByNome("São João do Triunfo") ?: new Cidade(estado: pr, nome: "São João do Triunfo").save()
		Cidade.findByNome("São Jorge do Oeste") ?: new Cidade(estado: pr, nome: "São Jorge do Oeste").save()
		Cidade.findByNome("São Jorge do Ivaí") ?: new Cidade(estado: pr, nome: "São Jorge do Ivaí").save()
		Cidade.findByNome("São Jorge do Patrocínio") ?: new Cidade(estado: pr, nome: "São Jorge do Patrocínio").save()
		Cidade.findByNome("São José da Boa Vista") ?: new Cidade(estado: pr, nome: "São José da Boa Vista").save()
		Cidade.findByNome("São José das Palmeiras") ?: new Cidade(estado: pr, nome: "São José das Palmeiras").save()
		Cidade.findByNome("São José dos Pinhais") ?: new Cidade(estado: pr, nome: "São José dos Pinhais").save()
		Cidade.findByNome("São Manoel do Paraná") ?: new Cidade(estado: pr, nome: "São Manoel do Paraná").save()
		Cidade.findByNome("São Mateus do Sul") ?: new Cidade(estado: pr, nome: "São Mateus do Sul").save()
		Cidade.findByNome("São Miguel do Iguaçu") ?: new Cidade(estado: pr, nome: "São Miguel do Iguaçu").save()
		Cidade.findByNome("São Pedro do Iguaçu") ?: new Cidade(estado: pr, nome: "São Pedro do Iguaçu").save()
		Cidade.findByNome("São Pedro do Ivaí") ?: new Cidade(estado: pr, nome: "São Pedro do Ivaí").save()
		Cidade.findByNome("São Pedro do Paraná") ?: new Cidade(estado: pr, nome: "São Pedro do Paraná").save()
		Cidade.findByNome("São Sebastião da Amoreira") ?: new Cidade(estado: pr, nome: "São Sebastião da Amoreira").save()
		Cidade.findByNome("São Tomé") ?: new Cidade(estado: pr, nome: "São Tomé").save()
		Cidade.findByNome("Sapopema") ?: new Cidade(estado: pr, nome: "Sapopema").save()
		Cidade.findByNome("Sarandi") ?: new Cidade(estado: pr, nome: "Sarandi").save()
		Cidade.findByNome("Saudade do Iguaçu") ?: new Cidade(estado: pr, nome: "Saudade do Iguaçu").save()
		Cidade.findByNome("Sengés") ?: new Cidade(estado: pr, nome: "Sengés").save()
		Cidade.findByNome("Serranópolis do Iguaçu") ?: new Cidade(estado: pr, nome: "Serranópolis do Iguaçu").save()
		Cidade.findByNome("Sertaneja") ?: new Cidade(estado: pr, nome: "Sertaneja").save()
		Cidade.findByNome("Sertanópolis") ?: new Cidade(estado: pr, nome: "Sertanópolis").save()
		Cidade.findByNome("Siqueira Campos") ?: new Cidade(estado: pr, nome: "Siqueira Campos").save()
		Cidade.findByNome("Sulina") ?: new Cidade(estado: pr, nome: "Sulina").save()
		Cidade.findByNome("Tamarana") ?: new Cidade(estado: pr, nome: "Tamarana").save()
		Cidade.findByNome("Tamboara") ?: new Cidade(estado: pr, nome: "Tamboara").save()
		Cidade.findByNome("Tapejara") ?: new Cidade(estado: pr, nome: "Tapejara").save()
		Cidade.findByNome("Tapira") ?: new Cidade(estado: pr, nome: "Tapira").save()
		Cidade.findByNome("Teixeira Soares") ?: new Cidade(estado: pr, nome: "Teixeira Soares").save()
		Cidade.findByNome("Telêmaco Borba") ?: new Cidade(estado: pr, nome: "Telêmaco Borba").save()
		Cidade.findByNome("Terra Boa") ?: new Cidade(estado: pr, nome: "Terra Boa").save()
		Cidade.findByNome("Terra Rica") ?: new Cidade(estado: pr, nome: "Terra Rica").save()
		Cidade.findByNome("Terra Roxa") ?: new Cidade(estado: pr, nome: "Terra Roxa").save()
		Cidade.findByNome("Tibagi") ?: new Cidade(estado: pr, nome: "Tibagi").save()
		Cidade.findByNome("Tijucas do Sul") ?: new Cidade(estado: pr, nome: "Tijucas do Sul").save()
		Cidade.findByNome("Toledo") ?: new Cidade(estado: pr, nome: "Toledo").save()
		Cidade.findByNome("Tomazina") ?: new Cidade(estado: pr, nome: "Tomazina").save()
		Cidade.findByNome("Três Barras do Paraná") ?: new Cidade(estado: pr, nome: "Três Barras do Paraná").save()
		Cidade.findByNome("Tunas do Paraná") ?: new Cidade(estado: pr, nome: "Tunas do Paraná").save()
		Cidade.findByNome("Tuneiras do Oeste") ?: new Cidade(estado: pr, nome: "Tuneiras do Oeste").save()
		Cidade.findByNome("Tupãssi") ?: new Cidade(estado: pr, nome: "Tupãssi").save()
		Cidade.findByNome("Turvo") ?: new Cidade(estado: pr, nome: "Turvo").save()
		Cidade.findByNome("Ubiratã") ?: new Cidade(estado: pr, nome: "Ubiratã").save()
		Cidade.findByNome("Umuarama") ?: new Cidade(estado: pr, nome: "Umuarama").save()
		Cidade.findByNome("União da Vitória") ?: new Cidade(estado: pr, nome: "União da Vitória").save()
		Cidade.findByNome("Uniflor") ?: new Cidade(estado: pr, nome: "Uniflor").save()
		Cidade.findByNome("Uraí") ?: new Cidade(estado: pr, nome: "Uraí").save()
		Cidade.findByNome("Wenceslau Braz") ?: new Cidade(estado: pr, nome: "Wenceslau Braz").save()
		Cidade.findByNome("Ventania") ?: new Cidade(estado: pr, nome: "Ventania").save()
		Cidade.findByNome("Vera Cruz do Oeste") ?: new Cidade(estado: pr, nome: "Vera Cruz do Oeste").save()
		Cidade.findByNome("Verê") ?: new Cidade(estado: pr, nome: "Verê").save()
		Cidade.findByNome("Alto Paraíso") ?: new Cidade(estado: pr, nome: "Alto Paraíso").save()
		Cidade.findByNome("Doutor Ulysses") ?: new Cidade(estado: pr, nome: "Doutor Ulysses").save()
		Cidade.findByNome("Virmond") ?: new Cidade(estado: pr, nome: "Virmond").save()
		Cidade.findByNome("Vitorino") ?: new Cidade(estado: pr, nome: "Vitorino").save()
		Cidade.findByNome("Xambrê") ?: new Cidade(estado: pr, nome: "Xambrê").save()
		*/
		
		
		///Definição de da congregação Sede
		if(!Congregacao.findByNome(Congregacao.SEDE)){
			Endereco enderecoSede = new Endereco(pais: bra, estado: pr, cidade: mga, bairro:"Operaria", rua: "Av. Mauá", numero: "1008").save()
			new Congregacao(nome: Congregacao.SEDE, endereco: enderecoSede).save()
		}
		
	}
	def destroy = {
	}
}
